version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
      POSTGRES_DB: book
    ports:
      - "19100:5432"

  mailhog:
    image: "mailhog/mailhog:latest"
    logging:
      driver: "none" # disable saving logs
    ports:
      - "19998:1025" # smtp server
      - "19997:8025" # web ui
    restart: always

volumes:
  db_data:
